language: objective-c
osx_image: xcode7.1
sudo: false

script:
  - xctool -project ByteBackpacker.xcodeproj -scheme ByteBackpacker\ iOS build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
- bash <(curl -s https://codecov.io/bash) 