language: objective-c
osx_image: xcode7.2
sudo: false

script:
- xcodebuild test -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker iOS" -destination "platform=iOS Simulator,name=iPhone 6"
- xcodebuild test -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker OS X"

after_success:
- bash <(curl -s https://codecov.io/bash) 